app/models/rickandmorty.py
import requests

class apiRickandMorty:

    def __init__(self, id, name, status, species, location, image):
        self.id = id
        self.name = name
        self.status = status
        self.species = species
        self.location = location
        self.image = image

    def to_json(self):
        return {
          "id": self.id,
          "name" : self.name,
          "status": self.status,
          "species": self.species,
          "location" : self.location,
          "image" : self.image
        }


    def getall_characters():
        listaall = []
        for i in range(1,22,1):
            result = requests.get(f'https://rickandmortyapi.com/api/character?page={i}')
            resultx= result.json()
            listaxpagina = resultx['results']
            listaall.append(listaxpagina)
        return listaall

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from app.config import Config
from app.routes.personajes import character_router
def create_app():
    app = Flask(__name__)
    
    app.config.from_object(Config)

    Bootstrap(app)

    app.register_blueprint(character_router)

    return app

app/routes/personajes.py
import hashlib
from flask import Blueprint, render_template, request, url_for, flash, redirect
from app.models.rickandmorty import apiRickandMorty
from app.db import db
from bson import ObjectId

import requests


character_router = Blueprint('character_router', __name__)

#mostrar todos
@character_router.route("/")
def index():
  #character = db.personajes.find() personajes=character
  personajes = db.apiRickandMorty.find()
  #return render_template("index.html", "avatar.html", ,avatar=avt)
  return render_template("index.html",personajes=personajes)


#mostrar solo un personaje
@character_router.route("/uno")
def uno(id=20,idx=8):
  
  character = db.personajes.find_one({"_id": ObjectId("6380e6599452a22bd1f14e36")})
  #character = db.personajes.find()
  
  
  apix = f'''https://rickandmortyapi.com/api/episode/{id}''' 
  respx = requests.get(apix)
  datox = respx.json()

  api = f'''https://rickandmortyapi.com/api/character?page={idx}''' 
  resp = requests.get(api)
  dato = resp.json()


 


  #return render_template("index.html", "avatar.html", ,avatar=avt)
  return render_template("uno.html", personajes=character, datox=datox, dato=dato)


#insertar personajes en mongodb
@character_router.route("/insertar_allpersonajes")
def insertar_allpersonajes():
    allpersonajes = apiRickandMorty.getall_characters()       
    for personajeXpagina in allpersonajes:                  
        for personaje in personajeXpagina:                     
            new_personaje = apiRickandMorty(
                id=str(personaje['id']),
                name=personaje['name'],
                status=personaje['status'],
                species=personaje['species'],
                location=personaje['location'],
                image=personaje['image']
            )

            db.apiRickandMorty.insert_one(new_personaje.to_json())
    
    return redirect(url_for('character_router.index'))


@character_router.route("/eliminar/<id>")
def delete_character(id):

  db.apiRickandMorty.delete_one({"id": id})

  flash("El personaje se elimino correctamente", "success")

  return redirect(url_for('character_router.index'))



@character_router.route('/prueba')
def prueba(id=8,idx=22):
    api = f'''https://rickandmortyapi.com/api/character?page={id}''' 
    resp = requests.get(api)
    dato = resp.json()
    
    apix = f'''https://rickandmortyapi.com/api/episode/{idx}''' 
    respx = requests.get(apix)
    datox = respx.json()

    return render_template("prueba.html", dato=dato, datox=datox)



#guardado de data en csv
def save_data_api():
    api = '''https://rickandmortyapi.com/api/character''' 

    for i in range(len(api)):
        resp = requests.get(api)
        dato = resp.json()


    archi1 = open('rickymorth.csv','w')
    archi1.write(str(dato))
    print(dato)


def lectura_api():
    for x in range(1,22,1):
      result = requests.get(f'https://rickandmortyapi.com/api/character?page={x}')
      detailPersonaje = result.json()
      for i in detailPersonaje['results']:
        print("Id:",i['id'])
        print("Name:",i['name'])
        print("Status:",i['status'])
        print("Species:",i['species'])
        print("Type:",i['type'])
        print("Gender:",i['gender'])
        print("Origin:" )
        print("    name:",i['origin']['name'])
        print("    url:",i['origin']['url'])
        print("Location:" )
        print("    name:",i['location']['name'])
        print("    name:",i['location']['url'])
        print("Image:",i['image'])
        print("Episode:")
        print("    episode:",i['episode'])
        print("Url:",i['url'])
        print("Created:",i['created'])
        print("        ")
        print("********************")

app/templates/avatar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">

    <title>Avatar</title>
</head>
<body>

    {% block content %}
    
    <img src="{{avatar}}" alt="">
    
    
    {% endblock %}
    
</body>
</html>

app/templates/base.html
{% extends "bootstrap/base.html" %} 



{% block body %}

<link href="//cdn.jsdelivr.net/npm/@sweetalert2/theme-dark@4/dark.css" rel="stylesheet">
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='css/grid.css' ) }}">
 <!-- Generamos una nueva variable de messages con sweetalert2 -->
 {% with messages = get_flashed_messages(with_categories=True) %}
     {% if messages %}
         {% for category, message in messages %}
             {% if category == 'error' %}
                 <script>
                     Swal.fire({
                        customClass: {
                         position: 'center',
                         icon: 'error',
                         width: 600,
                         height: 900,
                         text: "{{message}}",
                         showConfirmButton: true
                        },
                         timer: 4
                     })
                 </script>
             {% else %}
                 <script>
                     Swal.fire({
                         position: 'center',
                         icon: 'success',
                         text: "{{message}}",
                         showConfirmButton: true,
                         timer: 5000
                     })
                 </script>
             {% endif %}
         {% endfor %}
     {% endif %}
 {% endwith  %}

    {% for message in get_flashed_messages(category_filter=['error'])%}
    <div class="alert alert-danger alert-dismissible">
        <button class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %} {% block content %} {% endblock %}
    </div>

    {% block scripts %} {{ super() }} 
    {% endblock %} 
{% endblock %}




 <!-- sweetAlert2 -->
 

app/templates/index.html
{% extends "base.html" %} {% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/grid.css' ) }}">


<div class="contain-imag"> 
  <h1 class="text-center text-info"><strong>Rick and morty</strong> </h1>
  <marquee direction="right" id="move"><h3> API: https://rickandmortyapi.com</h3></marquee>
  <img src="{{ url_for('static', filename='img/portada.jpg') }}" class="img-thumbnail" />
  <hr>
  </div>

<div class="container">
  <div class="row">
    
    {% for i in personajes  %}
    <div class="col-xs-12 col-sm-6">
      <div class="card horizontal">
        <a href="#"></a>
        <img class="card-img-top" src="{{i.image}}" alt="Card image cap">
        <div class="card-body">


          <h4 class="card-text bg-gradient-warning text-primary" ><strong>{{i.name}}</strong></h3>
          <p class="card-subtitlex text-info">🔴 {{i.status}} - {{i.species}}</p>
          <h5 class="card-subtitle mb-2 text-success "><strong>Last known location: </strong></h5>
          <h5 class="card-subtitlelocation" id="sub"> {{i.location.name}}</h5>
          <h5 class="card-subtitle mb-2 text-success" id="spacio"><strong>First seen in: </strong></h5>
          <h5 class="card-subtitle mb-2" id="sub"> En el episodio 25 (Por hacer...)</h5>


        </div>
        <div class="card-footer">
          <div class="read__more"  style="visibility: hidden;"></div>
          <a href="" class="read__more btn ">Ver perfil</a>
          <a href="{{ url_for('character_router.delete_character', id=i.id) }}" class="btn btn-danger">
            Delete
          </a>

        </div>
      </div>
    </div>
    {% endfor %}
   
    
    
    

    
    
  </div>
</div>

{% endblock content %}

app/templates/prueba.html
{% extends "base.html" %} {% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/estilos.css' ) }}">
<h1>Ricky and morthy</h1>







<div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Status</th>
          <th>Species </th>
          <th>Gender</th>
          <th>Last know location</th>
          <th>Imagen</th>
          <th>First seen in</th>
        </tr>
      </thead>
      <tbody>
        {% for i in (dato['results']) %}
        <tr>
          <td>{{ i.id }}</td>
          <td>{{ i.name }}</td>
          <td>{{ i.status }}</td>
          <td>{{ i.species }}</td>
          <td>{{ i.gender }}</td>
          <td>{{ i.location.name }}</td>
          <td> <img src="{{ i.image }}" alt=""></td>

          <td>{{ datox.name }}</td>
          
        </tr>
    </tbody>
    {% endfor %}
</table>



      
    
  </div>
 

{% endblock content %}

app/templates/uno.html
{% extends "base.html" %} {% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/estilos.css' ) }}">


    <div class="container">
 
      <div class="contain-imag"> 
      <h1 class="text-center">Rick and morty </h1>
      <img src="{{ url_for('static', filename='img/portada.jpg') }}" class="img-thumbnail" />
      </div>


      <!-- inicio del div -->
      <div class="card float-right">
        <div class="row">
          <div class="col-sm-5">
            <img class="d-block w-100" src="{{personajes.image}}" alt="">
          </div>
          <div class="col-sm-7">
            <div class="card-block">
              <!--           <h4 class="card-title">Small card</h4> -->
              <h4 class="card-title"> <strong>{{personajes.name}}</strong></h4>
              <p class="card-subtitlex">🔴 {{personajes.status}} - {{personajes.species}}</p>
              

              <h5 class="card-subtitle mb-2 text-success "><strong>Last known location: <strong></h5>

                {% for i in (dato['results']) %}
                <h5 class="card-subtitlelocation"> {{ i.location.name}}</h5>
                {% endfor %}
                


              <h5 class="card-subtitle mb-2 text-success" id="spacio"><strong>First seen in: <strong></h5>
              <h5 class="card-subtitle mb-2 ">{{datox.name}}</h5>
              <a href="#" class="btn btn-primary float-right">Ver perfil</a>


            </div>
          </div>
          
          
   
        </div>
      
      </div>
    
      <!-- final del div -->


    </div>
   <br>
  <br>
 

  
  

{% endblock content %}